const fs = require('fs');
const path = require('path');

/**
 * UruTienda CSV safety rules:
 * - Start from an export generated by the store.
 * - Never delete Producto ID or Variante ID.
 * - Preserve every column that is not explicitly changed.
 * - Match existing products by Producto ID first; SKU/name only for diagnostics.
 */

function normalizeName(value = '') {
  return String(value).trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '');
}

function parseCsvLine(line) {
  const out = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (ch === '"') {
      if (quoted && line[i + 1] === '"') { field += '"'; i++; }
      else quoted = !quoted;
    } else if (ch === ',' && !quoted) {
      out.push(field); field = '';
    } else field += ch;
  }
  out.push(field);
  return out;
}

function csvEscape(value) {
  const s = value == null ? '' : String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function updateSingleProduct({ inputCsv, outputCsv, productId, changes }) {
  const raw = fs.readFileSync(inputCsv, 'utf8').replace(/^\uFEFF/, '');
  const lines = raw.split(/\r?\n/).filter((line, i, arr) => i < arr.length - 1 || line.length);
  const headers = parseCsvLine(lines[0]);
  const productIdIndex = headers.indexOf('Producto ID');
  if (productIdIndex < 0) throw new Error('No se encontró la columna Producto ID.');

  const indexes = {};
  for (const key of Object.keys(changes)) {
    indexes[key] = headers.indexOf(key);
    if (indexes[key] < 0) throw new Error(`Columna UruTienda inexistente: ${key}`);
  }

  let matches = 0;
  const output = [headers.map(csvEscape).join(',')];
  for (let i = 1; i < lines.length; i++) {
    const row = parseCsvLine(lines[i]);
    if (String(row[productIdIndex]).trim() === String(productId)) {
      matches++;
      for (const [key, value] of Object.entries(changes)) row[indexes[key]] = value;
    }
    output.push(row.map(csvEscape).join(','));
  }
  if (matches !== 1) throw new Error(`Seguridad: Producto ID ${productId} tuvo ${matches} coincidencias; se esperaba 1.`);
  fs.writeFileSync(outputCsv, '\uFEFF' + output.join('\r\n'), 'utf8');
  return { productId, matches, changedColumns: Object.keys(changes), outputCsv: path.resolve(outputCsv) };
}

module.exports = { normalizeName, updateSingleProduct };
